functionsDirectory = "/Users/ishikawasuguru/AI_コンサル/HP作成/site/netlify/functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/ishikawasuguru/AI_コンサル/HP作成/site"
publishOrigin = "default"
base = "/Users/ishikawasuguru/AI_コンサル/HP作成/site"
functions = "/Users/ishikawasuguru/AI_コンサル/HP作成/site/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]